#pragma config(Sensor, S1,     clap,           sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int clapcount
	while(true)
	{
		if(SensorValue(clap) > 50)
		{
			motor(motorA)= 50;
			wait1Msec(1500);
			motor(motorA) = -50;
		}
}
 while(SensorValue(clap) < 20)
 {
   motor(motorA)= 0:
 }


}
